#! /bin/dash

### BEGIN INIT INFO
# Short-Description:    LXD Container Hypervisor
# Description:          LXD Container Hypervisor
# Provides:             lxd
# Required-Start:       $remote_fs $network lxcfs
# Required-Stop:        $remote_fs $network lxcfs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
### END INIT INFO

# NOTE -- This sysvinit script isn't as well tested as its systemd counterpart,
#         but was verified to work on a bookworm/sid system in September 2022.
#         The host system must have a cgroup v2 hierarchy mounted.

DAEMON=/usr/bin/lxd
NAME=lxd
DESC="LXD Container Hypervisor"
PIDFILE=/run/lxd.pid

. /lib/lsb/init-functions

test -f ${DAEMON} || exit 0

set -e

START="-m --start --quiet --pidfile ${PIDFILE} --name ${NAME} --startas $DAEMON --background"
case "$1" in
    start)
        /usr/libexec/lxd/lxd-apparmor-load

        echo -n "Starting $DESC: "
        ulimit -n 65536
        [ -e /etc/environment ] && . /etc/environment
        if start-stop-daemon ${START} -- --group lxd --logfile=/var/log/lxd/lxd.log >/dev/null 2>&1 ; then
            echo "${NAME}."

            ${DAEMON} waitready --timeout=600
        else
            if start-stop-daemon --test ${START} >/dev/null 2>&1; then
                echo "(failed)."
                exit 1
            else
                echo "${DAEMON} already running."
                exit 0
            fi
        fi

        exit 0
    ;;

    stop)
        echo -n "Stopping $DESC: "
        if start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
            --startas ${DAEMON} --retry 10 --name ${NAME} \
            >/dev/null 2>&1 ; then
                echo "${NAME}."
        else
            if start-stop-daemon --test ${START} >/dev/null 2>&1; then
                echo "(not running)."
                exit 0
            else
                echo "(failed)."
                exit 1
            fi
        fi

        exit 0
    ;;

    status)
        status_of_proc -p ${PIDFILE} "${DAEMON}" lxd
    ;;

    restart|force-reload)
        $0 stop
        exec $0 start
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" 1>&2
        exit 1
    ;;
esac
